"""Repository protocols — the persistence boundary the rest of the package
depends on. Concrete implementations live in sibling ``json_*`` modules.

These are structural ``Protocol``s (not ABCs), so any class that exposes the
listed attributes/methods satisfies the contract — no inheritance needed.
This keeps the door open for in-memory test doubles or alternate backends
without coupling them to a specific base class.
"""

import threading
from pathlib import Path
from typing import Protocol

from ..dish import Dish
from ..inventory import InventoryItem
from ..plan import WeekPlan
from ..shopping_request import ShoppingRequest


class DishRepository(Protocol):
    """Persistence boundary for the dish catalog."""

    lock: threading.Lock

    def load(self) -> list[Dish]: ...
    def load_strict(self) -> list[Dish]: ...
    def save(self, dishes: list[Dish]) -> None: ...
    def restore(self, dish: Dish) -> bool: ...


class FridgeRepository(Protocol):
    """Persistence boundary for the fridge inventory."""

    lock: threading.Lock

    def load(self) -> list[str]: ...
    def load_set(self) -> set[str]: ...
    def load_items(self) -> list[InventoryItem]: ...
    def load_catalog_items(self) -> list[InventoryItem]: ...
    def resolve_ingredient(self, name: str, *, available_only: bool = False) -> InventoryItem | None: ...
    def save(self, ingredients: list[str]) -> None: ...
    def save_items(self, items: list[InventoryItem]) -> None: ...
    def add_item(self, **fields) -> InventoryItem: ...
    def replenish_item(self, *, item_id: str | None = None, name: str | None = None, **fields) -> InventoryItem: ...
    def receive_product(self, *, requested_name: str, exact_name: str, **fields) -> InventoryItem: ...
    def set_product_category(self, name: str | None, category: str, *, item_id: str | None = None, **kwargs) -> InventoryItem: ...
    def edit_item(self, item_id: str, patch: dict, *, expected_updated_at: str | None = None) -> InventoryItem: ...
    def remove_item(self, item_id: str, *, expected_updated_at: str | None = None) -> InventoryItem: ...
    def rename_by_name(self, old_name: str, new_name: str) -> InventoryItem: ...
    def remove_items(self, items: list[str]) -> None: ...


class HistoryRepository(Protocol):
    """Persistence boundary for cooking history.

    History is keyed by normalized dish name and value is an ISO date string.
    The repository owns its own locking — callers do not hold it.
    """

    def load(self) -> dict[str, str]: ...
    def set_entry(self, dish_name: str, date_str: str) -> str | None: ...
    def remove_entry(self, dish_name: str) -> bool: ...
    def revert_entry(
        self,
        dish_name: str,
        expected_value: str,
        previous_value: str | None,
    ) -> bool: ...


class PrepItemRepository(Protocol):
    """Persistence boundary for prep items (semi-finished products)."""

    lock: threading.Lock

    def load(self) -> list: ...
    def load_strict(self) -> list: ...
    def save(self, items: list) -> None: ...


class PlanRepository(Protocol):
    """Persistence boundary for one-file-per-week meal plans."""

    lock: threading.Lock
    plans_dir: Path

    def load(self, week_id: str) -> WeekPlan | None: ...
    def load_strict(self, week_id: str) -> WeekPlan | None: ...
    def save(self, plan: WeekPlan) -> None: ...
    def delete(self, week_id: str) -> bool: ...
    def list_weeks(self) -> list[dict]: ...


class ShoppingRequestRepository(Protocol):
    path: Path

    @property
    def lock(self): ...

    def load(self, *, week: str | None = None) -> list[ShoppingRequest]: ...
    def add(self, *, week: str, requested_name: str) -> ShoppingRequest: ...
    def get(self, request_id: str) -> ShoppingRequest | None: ...
    def get_completion(self, request_id: str) -> ShoppingRequest | None: ...
    def reserve_receipt(
        self, request_id: str, *, week: str, requested_name: str, exact_name: str
    ) -> ShoppingRequest: ...
    def complete(
        self, request_id: str, *, product_id: str, exact_name: str
    ) -> ShoppingRequest | None: ...
    def remove(self, request_id: str) -> ShoppingRequest | None: ...


class TuningRepository(Protocol):
    """Persistence boundary for the online suggestion-weight learner.

    State is a single JSON object (candidate grid, discounted reward/count
    sums, observation counter, deployed weights). ``load`` never raises —
    a missing or corrupt file yields a fresh initialized state. The lock is
    exposed so the cook handler can wrap the load-modify-save sequence.
    """

    lock: threading.Lock

    def load(self) -> dict: ...
    def save(self, state: dict) -> None: ...
